# Generated by Django 3.1.2 on 2020-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='答题人')),
                ('user_code', models.IntegerField(max_length=500, verbose_name='账号')),
                ('exam_name', models.CharField(max_length=500, verbose_name='活动名称')),
                ('time_limit', models.IntegerField(max_length=500, verbose_name='时间限制（分钟）')),
                ('times', models.CharField(default='无限制', max_length=500, verbose_name='可作答次数')),
                ('real_times', models.IntegerField(default='1', max_length=500, verbose_name='实际次数')),
                ('point', models.IntegerField(max_length=500, verbose_name='得分')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
    ]
