# Generated by Django 3.1.2 on 2020-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmexaminfo',
            name='point',
            field=models.IntegerField(verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='crmexaminfo',
            name='real_times',
            field=models.IntegerField(default='1', verbose_name='实际次数'),
        ),
        migrations.AlterField(
            model_name='crmexaminfo',
            name='time_limit',
            field=models.IntegerField(verbose_name='时间限制（分钟）'),
        ),
        migrations.AlterField(
            model_name='crmexaminfo',
            name='user_code',
            field=models.IntegerField(verbose_name='账号'),
        ),
    ]
