# Generated by Django 3.1.2 on 2020-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201119_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusiCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busi_code', models.IntegerField(verbose_name='业务代码')),
                ('busi_name', models.CharField(max_length=500, verbose_name='业务名称')),
                ('in_use', models.IntegerField(verbose_name='是否使用')),
                ('app_id', models.IntegerField(verbose_name='渠道名称')),
            ],
        ),
        migrations.CreateModel(
            name='BusiModelDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.IntegerField(verbose_name='模板编号')),
                ('source_no', models.IntegerField(verbose_name='扫描项代码')),
            ],
        ),
        migrations.CreateModel(
            name='BusiServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.IntegerField(verbose_name='模板编号')),
                ('app_id', models.IntegerField(verbose_name='渠道名称')),
                ('busi_code', models.IntegerField(verbose_name='业务代码')),
                ('cust_prop', models.IntegerField(verbose_name='机构类别')),
                ('in_active', models.IntegerField(verbose_name='是否使用')),
            ],
        ),
        migrations.CreateModel(
            name='SourceScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.IntegerField(verbose_name='扫描项代码')),
                ('source_name', models.CharField(max_length=500, verbose_name='扫描项名称')),
                ('source_type', models.IntegerField(verbose_name='类型')),
                ('in_use', models.IntegerField(verbose_name='是否使用')),
            ],
        ),
        migrations.AlterField(
            model_name='crmexaminfo',
            name='time_limit',
            field=models.IntegerField(default=60, verbose_name='时间限制（分钟）'),
        ),
    ]
