# Generated by Django 3.1.2 on 2020-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201203_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaninfo',
            name='app_id',
            field=models.CharField(max_length=500, verbose_name='渠道名称'),
        ),
    ]
