# Generated by Django 3.1.2 on 2021-01-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201203_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaninfo',
            name='busi_code',
            field=models.CharField(max_length=500, verbose_name='业务代码'),
        ),
    ]
