# Generated by Django 3.0.4 on 2020-03-24 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_type',
            field=models.CharField(default='jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 34, 36, 797951)),
        ),
    ]
