# Generated by Django 3.0.4 on 2020-03-25 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0002_auto_20200324_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='load_user',
            field=models.CharField(default='wansx', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 10, 6, 56, 642821)),
        ),
    ]
