# Generated by Django 3.0.4 on 2020-03-25 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0004_auto_20200325_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='is_personal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 14, 6, 56, 824135)),
        ),
    ]
