# Generated by Django 3.0.4 on 2020-03-26 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0005_auto_20200325_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='folder_name',
            field=models.CharField(default='Z:\\PYTHON_FILE\\', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_size',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_type',
            field=models.CharField(default='FOLDER', max_length=500),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
