# Generated by Django 3.0.4 on 2020-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0006_auto_20200326_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xqtj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('tj_path', models.CharField(max_length=500)),
            ],
        ),
    ]
