# Generated by Django 3.0.4 on 2020-04-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0007_xqtj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xqtj',
            new_name='Xqtj1',
        ),
    ]
