# Generated by Django 3.0.4 on 2020-04-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0008_auto_20200402_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xqtj1',
        ),
    ]
