# Generated by Django 3.1.2 on 2021-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=500, verbose_name='加班日期')),
                ('work_type', models.CharField(choices=[('工作日加班', '工作日加班'), ('周末测试', '周末测试')], default='周末测试', max_length=500, verbose_name='加班类型')),
                ('work_info', models.CharField(max_length=500, verbose_name='加班事项')),
                ('name', models.CharField(max_length=500, verbose_name='加班人员')),
                ('expense', models.IntegerField(default=60, verbose_name='时间限制（分钟）')),
                ('extra', models.CharField(max_length=500, verbose_name='补充说明')),
            ],
        ),
    ]
