# Generated by Django 3.0.4 on 2020-03-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jzyy_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
