# Generated by Django 3.0.4 on 2020-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzyy_notes', '0004_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_personal',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Public',
        ),
    ]
