# Generated by Django 3.1.2 on 2020-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzyy_notes', '0006_equipmentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
