# Generated by Django 3.0.4 on 2020-04-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='city',
            field=models.IntegerField(db_column='城市', default=0),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='competitor',
            field=models.CharField(db_column='同行竞争者', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_column='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(db_column='创建人', max_length=50),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='culture',
            field=models.CharField(db_column='企业文化', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_fullname',
            field=models.CharField(db_column='公司全称', max_length=100),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_name',
            field=models.CharField(db_column='公司简称', max_length=50),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_style',
            field=models.IntegerField(db_column='客户类型', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='develop_stage',
            field=models.IntegerField(db_column='发展阶段', default=0),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='email',
            field=models.CharField(db_column='邮件', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='establish',
            field=models.CharField(db_column='成立时间', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='finance',
            field=models.CharField(db_column='融资情况', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='interview_process',
            field=models.CharField(db_column='面试流程', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='introduction',
            field=models.CharField(db_column='客户简介', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='invoice',
            field=models.CharField(db_column='发票抬头', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='is_share',
            field=models.IntegerField(db_column='分享', default=0),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='location',
            field=models.CharField(db_column='地址', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='nature',
            field=models.CharField(db_column='企业性质', max_length=50),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='products',
            field=models.CharField(db_column='产品', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='profession',
            field=models.IntegerField(db_column='行业', default=0),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='salary_structure',
            field=models.CharField(db_column='薪资架构', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='size',
            field=models.CharField(db_column='公司规模', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='source',
            field=models.IntegerField(db_column='来源', default=0),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='tel',
            field=models.CharField(db_column='电话', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='value',
            field=models.CharField(db_column='公司年产值', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='website',
            field=models.CharField(db_column='网站', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='welfare1',
            field=models.CharField(db_column='福利(保险、公积金)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='welfare2',
            field=models.CharField(db_column='福利(餐住车补)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='work_category',
            field=models.CharField(db_column='工作类别', max_length=50),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='worktime',
            field=models.CharField(db_column='工作时间', max_length=50, null=True),
        ),
    ]
