# Generated by Django 3.0.4 on 2020-04-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_custcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_style',
            field=models.CharField(max_length=50, null=True, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='develop_stage',
            field=models.CharField(max_length=50, null=True, verbose_name='发展阶段'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='is_share',
            field=models.CharField(max_length=50, null=True, verbose_name='分享'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='profession',
            field=models.CharField(max_length=50, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='source',
            field=models.CharField(max_length=50, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='work_category',
            field=models.CharField(max_length=50, null=True, verbose_name='工作类别'),
        ),
    ]
