# Generated by Django 3.0.4 on 2020-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200413_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='profession',
            field=models.CharField(blank=True, choices=[(0, '上海'), (1, '北京')], max_length=50, null=True, verbose_name='行业'),
        ),
    ]
