# Generated by Django 3.0.4 on 2020-04-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200413_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', to_field='cust_name'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='公司简称'),
        ),
    ]
