# Generated by Django 3.0.4 on 2020-04-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200413_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='cust_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='公司简称'),
        ),
    ]
