# Generated by Django 3.0.4 on 2020-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20200414_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', to_field='cust_name', verbose_name='客户名称'),
        ),
    ]
