# Generated by Django 3.0.4 on 2020-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20200422_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(default='wansx', max_length=50, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
