# Generated by Django 3.1.2 on 2021-02-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='领导'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('部门总', '部门总'), ('副总', '副总'), ('总助', '总助'), ('职员', '职员')], default='职员', max_length=32, null=True, verbose_name='职级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
