# Generated by Django 3.0.4 on 2020-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='公司简称')),
                ('cust_fullname', models.CharField(max_length=100, verbose_name='公司全称')),
                ('invoice', models.CharField(max_length=50, verbose_name='发票抬头')),
                ('profession', models.IntegerField(default=0, verbose_name='行业')),
                ('city', models.IntegerField(default=0, verbose_name='城市')),
                ('tel', models.CharField(max_length=50, verbose_name='电话')),
                ('website', models.CharField(max_length=50, verbose_name='网站')),
                ('location', models.CharField(max_length=50, verbose_name='地址')),
                ('email', models.CharField(max_length=50, verbose_name='邮件')),
                ('finance', models.CharField(max_length=50, verbose_name='融资情况')),
                ('establish', models.CharField(max_length=50, verbose_name='成立时间')),
                ('source', models.IntegerField(default=0, verbose_name='来源')),
                ('develop_stage', models.IntegerField(default=0, verbose_name='发展阶段')),
                ('salary_structure', models.CharField(max_length=50, verbose_name='薪资架构')),
                ('products', models.CharField(max_length=50, verbose_name='产品')),
                ('size', models.CharField(max_length=50, verbose_name='公司规模')),
                ('competitor', models.CharField(max_length=50, verbose_name='同行竞争者')),
                ('worktime', models.CharField(max_length=50, verbose_name='工作时间')),
                ('welfare1', models.CharField(max_length=50, verbose_name='福利(保险、公积金)')),
                ('welfare2', models.CharField(max_length=50, verbose_name='福利(餐住车补)')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('nature', models.CharField(max_length=50, verbose_name='企业性质')),
                ('is_share', models.IntegerField(default=0, verbose_name='分享')),
                ('work_category', models.CharField(max_length=50, verbose_name='工作类别')),
                ('introduction', models.CharField(max_length=50, verbose_name='客户简介')),
                ('culture', models.CharField(max_length=50, verbose_name='企业文化')),
                ('interview_process', models.CharField(max_length=50, verbose_name='面试流程')),
                ('cust_style', models.IntegerField(default=0, verbose_name='客户类型')),
                ('value', models.CharField(max_length=50, verbose_name='公司年产值')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
