# Generated by Django 3.0.4 on 2020-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200413_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='cust_name',
            field=models.CharField(max_length=50, verbose_name='公司简称'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_style',
            field=models.CharField(blank=True, choices=[('普通公司', '普通公司'), ('开发中的客户', '开发中的客户'), ('已签约的客户', '已签约的客户'), ('历史客户', '历史客户'), ('自动生成', '自动生成')], max_length=50, null=True, verbose_name='客户类型'),
        ),
    ]
