# Generated by Django 3.0.4 on 2020-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200413_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='city',
            field=models.CharField(blank=True, choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳')], max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(blank=True, choices=[('wansx', 'wansx'), ('zhoulele', 'zhoulele')], max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='develop_stage',
            field=models.CharField(blank=True, choices=[('初创期', '初创期'), ('快速成长期', '快速成长期'), ('变革期', '变革期'), ('成熟期', '成熟期'), ('衰退期', '衰退期')], max_length=50, null=True, verbose_name='发展阶段'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='is_share',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=50, null=True, verbose_name='分享'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='nature',
            field=models.CharField(blank=True, choices=[('央企', '央企'), ('国企', '国企'), ('民企', '民企'), ('合资', '合资'), ('外企', '外企')], max_length=50, null=True, verbose_name='企业性质'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='profession',
            field=models.CharField(blank=True, choices=[('房地产', '房地产'), ('互联网', '互联网'), ('金融', '金融')], max_length=50, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='source',
            field=models.CharField(blank=True, choices=[('BD', 'BD'), ('公司线索', '公司线索'), ('内推', '内推')], max_length=50, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='website',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='网站'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='work_category',
            field=models.CharField(blank=True, choices=[('1', '1'), ('11', '11')], max_length=50, null=True, verbose_name='工作类别'),
        ),
    ]
