# Generated by Django 3.0.4 on 2020-04-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20200413_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(default='正荣地产', on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', to_field='cust_name'),
            preserve_default=False,
        ),
    ]
