# Generated by Django 3.0.4 on 2020-04-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_custcontact_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', to_field='cust_name', verbose_name='客户名称'),
        ),
    ]
