# Generated by Django 3.0.4 on 2020-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20200414_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人'),
        ),
    ]
