# Generated by Django 3.0.4 on 2020-04-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20200420_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', to_field='cust_name', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(blank=True, choices=[('choose', ''), ('wansx', 'wansx'), ('zhoulele', 'zhoulele')], max_length=50, null=True, verbose_name='创建人'),
        ),
    ]
