# Generated by Django 3.0.4 on 2020-04-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20200420_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='custcontact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='creator',
            field=models.CharField(blank=True, choices=[('wansx', 'wansx'), ('zhoulele', 'zhoulele')], max_length=50, null=True, verbose_name='创建人'),
        ),
    ]
