# Generated by Django 3.0.4 on 2020-04-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20200422_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustInfo', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='cust_name',
            field=models.CharField(max_length=50, verbose_name='公司简称'),
        ),
    ]
